### PR TITLE
Clean up Solid examples

### LINKED ISSUE #10: Organize Solid examples
Follow-up to the discussion from #8

### PR DESCRIPTION
**Pull request by NoelDeMartin**
Following up from #10, there are a couple of things I'm adding here (I can remove some if we don't want them):

- Restructured Solid examples: This goes in line to what we already discussed, in the end I decided to leave the index like before mentioning only one example. Then, inside of the main examples, we can link to the others. I think this should be less confusing for people interested in the 3 protocols, and for people specifically interested in Solid they'll find the other examples anyways.
- Added symlinks + vite config: This solves the problem of serving the app from the root or an individual folder. Although I would agree that it complicates the project more and maybe we don't like that :(. Let me know what you think.
- Cleaned up `solid-file-client` example. After some testing, I realized it is not doing error handling like the other example, so I refactored it to make them more similar. After doing this, I realized using this library is not much better than just doing `fetch`, so I'm not sure how useful this will be for newcomers. I'm not saying this because I don't like the library, it's just that for this use-case there is not too much difference (the library is very useful if you want to do more advanced features). But I guess we can leave it anyways for completeness if we're going to add more examples later on. @bourgeoa let me know if you have any comments about this.

### CODE REVIEW

**Review by rosano — APPROVED** [review]
Looks good to me and I think merge when possible. My comments are:

1. I'm not sure how the `main.js` files with a body of `../common/main.js` works in the browser. What is that?
2. Perhaps related to 1: do the Vite behaviours have any difference from the GitHub Pages deployment?
3. I wanted to document instructions for `php -S localhost:3000` as a start command, because it might be built into many operating systems. I'm not opposed to having multiple options. What do you think the tradeoffs are of each approach? Perhaps I should put this in an 'Issue'.

**Comment by NoelDeMartin** [comment]
> I'm not sure how the main.js files with a body of ../common/main.js works in the browser. What is that?

Yeah it's kind of weird seeing it here on github, it's just a symlink I created doing `ln -s ../common/main.js ./main.js`. I think it should work both in Ubuntu and Mac, and it doesn't work on windows but [it should be checked out as a text file](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks) if someone clones the repo.

I'm not super convinced about this, but the alternatives are either duplicating the common files, or linking the paths relatively like we were doing before. The drawback of using relative paths is that each example is no longer self-sufficient, you have to serve the application from the root of the repo. If you still prefer the initial approach I don't mind, but I guess now that we have files 3 levels deep we should clarify this point in the usage instructions.

> Perhaps related to 1: do the Vite behaviours have any difference from the GitHub Pages deployment?

The difference is that `vite .` can be run from subfolders, for example from `solid/solid-file-client`, and then you'd be running only that example, which I guess is the goal if we want to consider the examples stand-alone. Github Pages runs the entire app.

The Vite config I added allows using files outside of the root directory it's serving. In this case, files from `../../common` that are symlinked.

> I wanted to document instructions for php -S localhost:3000 as a start command, because it might be built into many operating systems. I'm not opposed to having multiple options. What do you think the tradeoffs are of each approach? Perhaps I should put this in an 'Issue'.

The only trade-off I can think of is increasing complexity, but I guess it's ok if we just list some options and people chose the one they like. In any case, these are plain html and JS files, so I guess most people who is trying to run the apps by themselves already knows how to run a local server. These are just suggestions in case somebody doesn't. It's a bummer that the app can't be run just double clicking on `index.html`, because that's what I'd like the most. But at least with Solid that doesn't work during the authentication flow.

**Comment by rosano** [comment]
Running from the root might be the simplest thing we can promise to ensure that everything works as expected, so I would focus on that and not worry about the subfolders.

> In any case, these are plain html and JS files, so I guess most people who is trying to run the apps by themselves already knows how to run a local server.

I assume most people don't know… On macOS `php` is bundled with the operating system, but I realize now it may not be the case for Windows or Linux, so then it might be just as complex to install Vite. Whatever's easiest I guess.

Thanks for cleaning up. Let's merge?

**Comment by NoelDeMartin** [comment]
> Running from the root might be the simplest thing we can promise to ensure that everything works as expected, so I would focus on that and not worry about the subfolders.

Yeah, I suppose that's ok. It'd be nice to have our cake and eat it too xD. Since you are fine going ahead with the merge, we can leave it as is for now and if anyone has issues with the symlink we just revert to using relative links and document the caveats of running the apps locally.

> I assume most people don't know… On macOS php is bundled with the operating system, but I realize now it may not be the case for Windows or Linux, so then it might be just as complex to install Vite. Whatever's easiest I guess.

Ok maybe most people don't know, I'm not sure who will end up looking at this repo anyways. I like the idea of using `php` because it's not coupled to npm which is kind of the point of not using a bundling system. But also, as you mention not everyone will have php installed (I use php and I don't have it installed because I run it with docker). So I don't know, I'm not against documenting multiple suggestions anyways.

> Thanks for cleaning up. Let's merge?

:+1:

**Pull request merged**
